version: "3.8"
services:
  node-app:
    # stdin_open: true
    # tty: true
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env